### ISSUE TITLE
Handle optional RMagick dependency more gracefully

### ISSUE THREAD

**Issue by jordanstephens** [jordanstephens/paleta#12]
Right now, Paleta has the functionality to generate a palette from an input image. This is handled in a method called `Paleta::Palette.generate_from_image`. Unfortunately, this method requires `RMagick`, which in turn requires ImageMagick, which is a rather large and often unwieldy dependency.

When writing this code originally, I wanted to try very hard to avoid requiring all users of Paleta to have ImageMagick installed when only one method in the library actually depended on it. In an attempt to accomplish this, I hacked together the situation you see at [lib/paleta/palette.rb#L4-L29](https://github.com/jordanstephens/paleta/blob/master/lib/paleta/palette.rb#L4-L29). Basically, we don't require `RMagick` at bundle time, but we do require it when we try to include a module of "MagickDependent" into `Paleta::Palette` at runtime. If `RMagick` is not successfully loaded, we print a message to the console to try to bring light to the situation.

I've been wanting to improve this for a long time, but after looking into #9, I wanted to open a new issue here to think about our options for moving forward.

I think the option that I would like to pursue at this point is to create a sort of "sister gem" to paleta, which will depend on `RMagick` and which will contain any "MagickDependent" methods. This gem will monkey-patch `include` these methods into `Paleta::Palette` at runtime. We will then replace the current "MagickDependent" methods with stubs which won't do anything other than print a line to the console to explain that they depend on this "sister gem" (these methods would be overwritten with the monkey-patch `include` if the sister gem is loaded in the bundle).

This would accomplish a number of things:
* Offload conditional dependency management to users, and reduce complexity in `Paleta::Palette` by removing the conditional dependency. (If users want the extra functionality, they will need to include the additional gem).
* Print warning messages when "MagickDependent" methods are called, rather than at module load-time.

In addition to this, though somewhat tangential, I'm going to look into replacing `RMagick` with `MiniMagick`.

If I don't hear anything on this in a while, I'll start to implement this vision when I have time.

cc @nadavshatz

**Comment by nadavshatz** [comment]
I think switching to MiniMagick would be a good call, I'm also involved with that project and it is much better maintained than RMagick (and faster).

I'm thinking having a separate gem monkey patching things at runtime might nit be the best course of action.
How about trying to load RMagick at load and setting a class variable to indicate if it worked, and at that point if any of the dependent methods get called they will `raise` an exception for missing the required dependency?
We can also set this variable as a config value if we prefer to make it explicit to the user.

Your thoughts?

**Comment by jordanstephens** [comment]
Good call @nadavshatz. I went ahead and threw together a first pass following your advice over at #13. Let me know what you think before I merge it.

**Comment by jordanstephens** [comment]
Also, at first glance, it doesn't look like we could migrate to mini_magick because it doesn't support rmagick's `ImageList`. I really want to remove the ImageMagick dependency. I might take a swing at bringing a quantization algorithm into paleta, since that's all that we're using ImageMagick for anyway.
