### ISSUE TITLE
Similarity doesn't work properly

### ISSUE THREAD

**Issue by quatermain** [jordanstephens/paleta#16]
```
color = Paleta::Color.new(:hex, '000202')
color2 = Paleta::Color.new(:hex, '000102')
color.similarity(color2)
#=> 0.002264118702704415
```

And I think these colors are very similar :) 
000202
![screen shot 2015-12-16 at 18 49 10](https://cloud.githubusercontent.com/assets/1125806/11848971/b7b112ce-a425-11e5-9db1-41587a49636f.png)
000102
![screen shot 2015-12-16 at 18 48 33](https://cloud.githubusercontent.com/assets/1125806/11848947/a92272a2-a425-11e5-90cf-697d1eb241e5.png)
I don't understand or is this issue? 
btw: thank you for very good gem

**Comment by jordanstephens** [comment]
@quatermain Sorry for the late response, I must have missed the notification. This results seems reasonable. The readme explains how this method works:

> The similarity method returns a value between 0 and 1, with 0 being identical and 1 being as dissimilar as possible.

So with these two colors being very similar, a similarity value close to 0 is not surprising. If the number was close to 1, then that would suggest an issue with the code.

I hope that helps.
