### ISSUE TITLE
RGB colors does not seem right

### ISSUE THREAD

**Issue by tomaszgiba** [jordanstephens/paleta#17]
Given a color `#ff7fec` it has actual RGB values: `R:236, G:255, B:127` (http://www.colorhexa.com/ecff7f)
However:

`Paleta::Color.new(:hex, 'ff7fec')` 

produces this object:

```
#<Paleta::Color:0x007fdfe9bf8058 @blue=236, @green=127, @hex="FF7FEC", @hue=308.90625, @lightness=74.90196078, @red=255, @saturation=100.0>
```

which has wrong red, green, blue values: `... @blue=236, @green=127... @red=255`
and it's returned wrong when `to_array` is used:

```
[25] pry(main)> Paleta::Color.new(:hex, '#ff7fec').to_array
=> [255, 127, 236]
```

**Comment by jordanstephens** [comment]
Hi @tomaszgiba 

The link you pasted is for `#ecff7f`, not `#ff7fec` which is what you ran through paleta.

`#ff7fec` is definitely `rgb(255, 127, 236)`, which is what paleta returned.

Also be careful to note that the website you are linking to shows RGB values on a 0..100 scale, whereas paleta uses a 0..255 scale.

Hope that helps!

**Comment by tomaszgiba** [comment]
Sorry, I was on a wild bug hunt. You are obviously right.

Thanks @jordanstephens
