### ISSUE TITLE
Support three character hex codes

### ISSUE THREAD

**Issue by lbain** [jordanstephens/paleta#6]
Some of the hex codes I'm working with only have three characters (`#ccc`). It'd be great if `Paleta::Color.new(:hex, color)` could support this.

Thanks!

**Comment by nadavshatz** [comment]
Thats a great idea! I'll add support for that and for leaving the '#' in there.

**Comment by lbain** [comment]
Wow, that was crazy fast! Thanks so much for working on it :)

**Comment by jordanstephens** [comment]
Just pushed v0.2.2 with this fix up to rubygems.

Thanks everyone!
