### ISSUE TITLE
 You must install RMagick to use Palette.generate(:from => :image, ...)

### ISSUE THREAD

**Issue by firedev** [jordanstephens/paleta#9]
Hi,

Please consider removing the warning if I am not using `Palette.generate`. It is excessive and gets in a way of console operations.

Thanks.

**Comment by jordanstephens** [comment]
I totally agree; this is a good idea.

Unfortunately this is kind of tangled up in the mess of handling an optional dependency. Right now, the placement of the message is wrapped up in the way the optional `RMagick` dependency is loaded. I would really like to completely re-evaluate how to handle this, as it's not handled in the most graceful way right now. (https://github.com/jordanstephens/paleta/blob/master/lib/paleta/palette.rb#L4-L29)

I'm actually not very happy with the optional `RMagick` (and thus ImageMagick) dependency at all. I would really like to find a more light-weight alternative, but I'm not sure what our options are right now.

As I'm writing this, another option just occurred to me. We could possibly create a sort of "sister gem" which would depend on `RMagick` and which would monkey patch the "generate from image" methods into `Paleta::Palette`. Then we could stub that method in the main `paleta` gem to explain to the user that the sister gem is required for the "generate from image" functionality. This would offload the dependency management to the user, reduce complexity in `Paleta::Palette`, and warn about the extra dependency at a more appropriate time. I'm going to close this for now, and open up another issue to discuss these options. Hopefully we can solve this issue in the process.

Thanks.

cc @nadavshatz

**Comment by jordanstephens** [comment]
@firedev this will get solved when #13 get's merged.
